// Live Casino Win — floor scatter geometry.
// DEPRECATED SHIM: values live in liveConfig.js (the single master
// tuning file). Edit liveConfig.js, not this file.

import {
    LIVE_FLOOR_ASPECT_W, LIVE_FLOOR_ASPECT_H,
    LIVE_FLOOR_X_MIN, LIVE_FLOOR_X_MAX, LIVE_FLOOR_Y_MIN, LIVE_FLOOR_Y_MAX,
    LIVE_SYMBOL_SIZE_DEFAULT, LIVE_SYMBOL_SIZE_MIN, LIVE_SYMBOL_SIZE_MAX, LIVE_SYMBOL_SIZE_STEP,
} from './liveConfig';

export {
    LIVE_FLOOR_ASPECT_W, LIVE_FLOOR_ASPECT_H,
    LIVE_FLOOR_X_MIN, LIVE_FLOOR_X_MAX, LIVE_FLOOR_Y_MIN, LIVE_FLOOR_Y_MAX,
    LIVE_SYMBOL_SIZE_DEFAULT, LIVE_SYMBOL_SIZE_MIN, LIVE_SYMBOL_SIZE_MAX, LIVE_SYMBOL_SIZE_STEP,
};
export const LIVE_FLOOR_ASPECT = `${LIVE_FLOOR_ASPECT_W} / ${LIVE_FLOOR_ASPECT_H}`;
